AllCops:
  TargetRubyVersion: 2.6
Rails:
  Enabled: true
Style/NumericLiterals:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
# Style/HashSyntax:
#   Enabled: false
# Style/StringLiterals:
#   Enabled: false
# Style/AsciiComments:
#   Enabled: false
# Style/TrailingCommaInHashLiteral:
#   Enabled: false
# Style/EmptyMethod:
#   Enabled: false
# Layout/SpaceInsideBlockBraces:
#   Enabled: false
# Layout/SpaceInsideHashLiteralBraces:
#   Enabled: false
# Layout/SpaceAfterComma:
#   Enabled: false
