version: "3.8"
services:
  checkparam:
    build: .
    tty: true
    volumes:
      - ..:/var/www:cached
      - vendor:/var/www/vendor
    environment:
      - BUNDLE_PATH=/var/www/vendor/bundle
      - EDITOR=code --wait
      - RAILS_ENV=production
      - RAILS_LOG_TO_STDOUT=1
  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: checkparam
    volumes:
      - mysql:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mysql
    tmpfs: /sessions
    ports:
      - 8080:80
volumes:
  vendor:
  mysql:
