version: "3.8"
services:
  checkparam:
    build: .
    tty: true
    working_dir: /var/www
    environment:
      - RAILS_LOG_TO_STDOUT=1
      - RAILS_SERVE_STATIC_FILES=1
    volumes:
      - ..:/var/www:cached
      - ~/.aws:/root/.aws:ro
      - /var/run/docker.sock:/var/run/docker.sock
