version: "3.2"
services:
  checkparam:
    build: .
    tty: true
    volumes:
      - ..:/var/www:delegated
    environment:
      - BUNDLE_PATH=/var/www/vendor/bundle
      - EDITOR='code --wait'
  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: development
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mysql
    tmpfs: /sessions
    ports:
      - 8080:80
